INSERT INTO ESTADOS (ID, NOME, SIGLA, REGIAO, POPULACAO)
VALUES (1000, 'NOVO', 'NV', 'SUL', 2.59);


SELECT * FROM ESTADOS;


INSERT INTO ESTADOS (NOME, SIGLA, REGIAO, POPULACAO)
VALUES ('MAIS NOVO', 'MN', 'NORTE', 2.51);




