-- ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'password';


CREATE TABLE ESTADOS (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  SIGLA VARCHAR(2) NOT NULL,
  REGIAO ENUM('NORTE', 'NORDESTE', 'CENTRO-OESTE', 'SUDESTE', 'SUL') NOT NULL,
  POPULACAO DECIMAL(5, 2) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (NOME),
  UNIQUE KEY (SIGLA)
);

